package org.cytoscape.gfdnet.view.configurationDialogs;

import org.cytoscape.gfdnet.controller.CoreController;
import org.cytoscape.gfdnet.controller.utils.CySwing;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class ConfigurateDBView extends javax.swing.JDialog {
    private final CoreController core;
    /**
     * Creates new form ConfigurateDBView
     */
    public ConfigurateDBView(CoreController core) {
        super(CySwing.getDesktopJFrame(), true);
        this.core = core;
        initComponents();
        setLocationRelativeTo(CySwing.getDesktopJFrame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OnlineConnectionButton = new javax.swing.JButton();
        LocalConnectionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        OnlineConnectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/OnlineCon.png"))); // NOI18N
        OnlineConnectionButton.setText("Online Connection");
        OnlineConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnlineConnectionButtonActionPerformed(evt);
            }
        });

        LocalConnectionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LocalCon.png"))); // NOI18N
        LocalConnectionButton.setText("Local Connection");
        LocalConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalConnectionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OnlineConnectionButton)
                    .addComponent(LocalConnectionButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OnlineConnectionButton)
                .addGap(18, 18, 18)
                .addComponent(LocalConnectionButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocalConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalConnectionButtonActionPerformed
        CySwing.displayDialog(new ConfigurateLocalDBConnectionView(core));
        this.dispose();
    }//GEN-LAST:event_LocalConnectionButtonActionPerformed

    private void OnlineConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnlineConnectionButtonActionPerformed
        core.configurateDB("mysql.ebi.ac.uk:4085/go_latest", "go_select", "amigo");
        dispose();
    }//GEN-LAST:event_OnlineConnectionButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LocalConnectionButton;
    private javax.swing.JButton OnlineConnectionButton;
    // End of variables declaration//GEN-END:variables
}
