package org.cytoscape.gfdnet.view.configurationDialogs;

import java.util.List;
import org.cytoscape.gfdnet.controller.CoreController;
import org.cytoscape.gfdnet.controller.utils.CySwing;
import org.cytoscape.gfdnet.model.businessobjects.go.Organism;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class SetOrganismSecondaryView extends javax.swing.JDialog {
    private CoreController core;
    private final String[] genus;
    private String[] species;
    /**
     * Creates new form SetOrganismSecView
     * @param c
     * @param preloadOrganism
     */
    public SetOrganismSecondaryView(CoreController core, boolean preloadOrganism) {
        super(CySwing.getDesktopJFrame(), true);
        this.core = core;
        List<String> speciesAux = Organism.getAllGenera();
        genus = new String[speciesAux.size()];
        for (int i = 0; i< speciesAux.size(); i++){
            genus[i] = speciesAux.get(i);
        }
        initComponents();
        PreloadOrganismCheckBox.setSelected(preloadOrganism);
        setLocationRelativeTo(CySwing.getDesktopJFrame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        genusList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        speciesList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AcceptButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        PreloadOrganismCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        genusList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = genus;
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        genusList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                genusListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(genusList);

        jScrollPane2.setViewportView(speciesList);

        jLabel1.setText("Choose genus:");

        jLabel2.setText("Choose specie:");

        AcceptButton.setText("Accept");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        PreloadOrganismCheckBox.setText("Preload organism");
        PreloadOrganismCheckBox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(AcceptButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CancelButton))
                .addContainerGap())
            .addComponent(PreloadOrganismCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AcceptButton)
                    .addComponent(CancelButton))
                .addGap(8, 8, 8)
                .addComponent(PreloadOrganismCheckBox))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genusListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_genusListValueChanged
        String curGenus = genusList.getSelectedValue().toString();
        List<String> speciesAux = Organism.getSpeciesFromGenus(curGenus);
        species = speciesAux.toArray(new String[speciesAux.size()]);
        speciesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = species;
            @Override
            public int getSize() { return strings.length; }
            @Override
            public Object getElementAt(int i) { return strings[i]; }
        });    
    }//GEN-LAST:event_genusListValueChanged

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
        Object selectedGenus = genusList.getSelectedValue();
        Object selectedSpecie = speciesList.getSelectedValue();
        if (selectedGenus != null && selectedSpecie != null){
            String genusS = selectedGenus.toString();
            String specieS = selectedSpecie.toString();
            core.setOrganism(genusS, specieS, PreloadOrganismCheckBox.isSelected());
            dispose();
        }
        else{
            CySwing.displayPopUpMessage("A genus and a specie must be selected.");
        }
    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JCheckBox PreloadOrganismCheckBox;
    private javax.swing.JList genusList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList speciesList;
    // End of variables declaration//GEN-END:variables
}