package org.cytoscape.gfdnet.view.configurationDialogs;

import org.cytoscape.gfdnet.controller.CoreController;
import org.cytoscape.gfdnet.controller.utils.CySwing;
import org.cytoscape.gfdnet.model.businessobjects.go.Ontology;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class SetOntologyView extends javax.swing.JDialog {
    private CoreController core;
    /**
     * Creates new form setOntologyV
     */
    public SetOntologyView(CoreController core) {
        super(CySwing.getDesktopJFrame(), true);
        this.core = core;
        initComponents();
        setLocationRelativeTo(CySwing.getDesktopJFrame());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BPbutton = new javax.swing.JButton();
        CCbutton = new javax.swing.JButton();
        MFbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        BPbutton.setText("Biological Process");
        BPbutton.setActionCommand("BP");
        BPbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPbuttonActionPerformed(evt);
            }
        });

        CCbutton.setText("Cellular Component");
        CCbutton.setActionCommand("CC");
        CCbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCbuttonActionPerformed(evt);
            }
        });

        MFbutton.setText("Molecular Function");
        MFbutton.setActionCommand("MF");
        MFbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BPbutton)
                    .addComponent(MFbutton)
                    .addComponent(CCbutton))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BPbutton)
                .addGap(18, 18, 18)
                .addComponent(CCbutton)
                .addGap(18, 18, 18)
                .addComponent(MFbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BPbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPbuttonActionPerformed
        core.setOntology(Ontology.BP);
        dispose();
    }//GEN-LAST:event_BPbuttonActionPerformed

    private void CCbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCbuttonActionPerformed
        core.setOntology(Ontology.CC);
        dispose();
    }//GEN-LAST:event_CCbuttonActionPerformed

    private void MFbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFbuttonActionPerformed
        core.setOntology(Ontology.MF);
        dispose();
    }//GEN-LAST:event_MFbuttonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BPbutton;
    private javax.swing.JButton CCbutton;
    private javax.swing.JButton MFbutton;
    // End of variables declaration//GEN-END:variables
}
