package org.cytoscape.gfdnet.view.resultPanel;

import java.math.BigDecimal;
import org.cytoscape.gfdnet.controller.ResultPanelsController;
import org.cytoscape.gfdnet.model.businessobjects.GeneInput;

/**
 * @license Apache License V2 <http://www.apache.org/licenses/LICENSE-2.0.html>
 * @author Juan José Díaz Montaña
 */
public class EdgeResultsPanel extends javax.swing.JPanel {
    private final ResultPanelsController resultPanels;
    /**
     * Creates new form DefaultResultsPanel
     * @param c
     */
    public EdgeResultsPanel(ResultPanelsController resultPanels) {
        initComponents();
        this.resultPanels = resultPanels;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gene2RepresentationValue = new javax.swing.JTextField();
        Gene1RepresentationValue = new javax.swing.JTextField();
        gene1Label = new javax.swing.JLabel();
        RLabel = new javax.swing.JLabel();
        gene2Label = new javax.swing.JLabel();
        RValue = new javax.swing.JTextField();

        Gene2RepresentationValue.setEditable(false);
        Gene2RepresentationValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gene2RepresentationValue.setText("Gene2Representation");
        Gene2RepresentationValue.setBorder(null);
        Gene2RepresentationValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Gene1RepresentationValue.setEditable(false);
        Gene1RepresentationValue.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gene1RepresentationValue.setText("Gene1Representation");
        Gene1RepresentationValue.setBorder(null);
        Gene1RepresentationValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        gene1Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gene1Label.setText("Gene 1:");
        gene1Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gene1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gene1LabelMouseClicked(evt);
            }
        });

        RLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        RLabel.setText("Relationship dissimilarity:");

        gene2Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gene2Label.setText("Gene 2");
        gene2Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gene2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gene2LabelMouseClicked(evt);
            }
        });

        RValue.setEditable(false);
        RValue.setText("R");
        RValue.setBorder(null);
        RValue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(gene1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(RLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RValue, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addComponent(Gene1RepresentationValue, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gene2RepresentationValue, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gene2Label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gene1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gene1RepresentationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gene2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Gene2RepresentationValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RLabel)
                    .addComponent(RValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gene1LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gene1LabelMouseClicked
        if (evt.getClickCount() == 1) {
            resultPanels.selectNode(gene1Label.getText());
        }
        else if (evt.getClickCount() == 2) {
            resultPanels.showNodeInfo(gene1Label.getText());
        }
    }//GEN-LAST:event_gene1LabelMouseClicked

    private void gene2LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gene2LabelMouseClicked
        if (evt.getClickCount() == 1) {
            resultPanels.selectNode(gene2Label.getText());
        }
        else if (evt.getClickCount() == 2) {
            resultPanels.showNodeInfo(gene2Label.getText());
        }
    }//GEN-LAST:event_gene2LabelMouseClicked

    public void updateView(GeneInput gene1, GeneInput gene2, BigDecimal similarity){
        gene1Label.setText(gene1.getName());
        Gene1RepresentationValue.setText(gene1.getRepresentationSelected().getGoTerm().getDescription());
        gene2Label.setText(gene2.getName());
        Gene2RepresentationValue.setText(gene2.getRepresentationSelected().getGoTerm().getDescription());
        RValue.setText(similarity.toPlainString());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Gene1RepresentationValue;
    private javax.swing.JTextField Gene2RepresentationValue;
    private javax.swing.JLabel RLabel;
    private javax.swing.JTextField RValue;
    private javax.swing.JLabel gene1Label;
    private javax.swing.JLabel gene2Label;
    // End of variables declaration//GEN-END:variables
}
